<a href="https://colab.research.google.com/github/M-Mag25/github-slideshow/blob/master/Stage_A_Lesson_2_by_MAGRET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#convention for importing numpy
import numpy as np
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)


<class 'numpy.ndarray'>
(4,)
int64


In [ ]:
#get the dimension of a width ndim
print(a.ndim)

b =np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.ndim) #b.ndim did not give any output until I put print
b.shape #or print(b.shape)

1
[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [ ]:
#import numpy as np
arr= [6, 7, 8, 9]
print(type(arr))
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)

<class 'list'>
<class 'numpy.ndarray'>
(4,)
int64


In [ ]:
#get the dimension of a width ndim
print(a.ndim)
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.shape)# or I can use b.shape after print(b.ndim) butif I use b.shape alone before print(b.ndim), there's no output
print(b.ndim)
print(b.dtype)


1
[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64


In [ ]:
# Inbuilt function that can be use to initialize numpy which include empty(), zeros(), ones(), full(), random.random().
# a 2*3 array with random values
np.random.random((2, 3))
#a 2*3 arrays of zeros
np.zeros((2,3))
# a 2*3 array of ones
np.ones((2,3))
# a 3*3 identity matrix
np.identity((3))


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Intra-operability of arrays and scalars
c = np.array([[9.0, 8.0,7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])
c + d
c*d
5/d
5/c
c**2
d**2
print(type(c))
arr= [[9.0, 8.0,7.0], [1.0, 2.0, 3.0]]
print(type(arr))
print(c.shape)
print(d.shape)
print(c.ndim)
print(c.dtype)
print(d.dtype)
np.random.random((2, 3))


<class 'numpy.ndarray'>
<class 'list'>
(2, 3)
(2, 3)
2
float64
float64


array([[0.57956875, 0.38305677, 0.0387218 ],
       [0.4572233 , 0.43000015, 0.08532518]])

In [ ]:
#Indexing with arrays and AMP; using arrays and data processing.
a[0]
a[1]
a[2]
a[3]
b[0, 0]
b[0, 1]
#b[0, 2]
#b[1, 0]
#b[1, 1]
#b[1, 2]
#c[0 ,0]
#c[0, 1]
#c[0, 2]
#c[1, 0]
#c[1, 1]
#c[1, 2]


2

In [ ]:
# Elements in arrays can be retrieved by slicing rows and columns or a combination of indexing and slicing
d[1, 0:2] 
d[0, 0:2]
c[0, 0:2]
c[1, 0:2]
c[0, 0:1]
c[1, 0:1]

e = np.array([[10, 11, 12], [13, 14,15], [16, 17, 18], [19, 20, 21]])

#SLICING
e[:3, :2]
e[:2, :3]
e[:2, :2]
e[:1, :3]
e[:1, :2]
e[:3, :1]
e[:3, :3]
e[:4, :2]
e[:4, : 3]
e[:4, :4]#this is the same with e[:4, :3]


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
#Other Advanced methods of indexing 
#Interer Indexing
e[[2, 0, 3, 1], [2, 1, 0, 2]] 

#Boolean indexing meeting a specified condition
e[e>15]

array([16, 17, 18, 19, 20, 21])